theme = "catppuccin_mocha"

[keys.insert]
C-h = ":buffer-previous"
C-l = ":buffer-next"
C-j = ":buffer-close"
C-s = ":write-all"
C-q = ":write-quit-all"

[keys.normal]
C-h = ":buffer-previous"
C-l = ":buffer-next"
C-j = ":buffer-close!"
C-s = ":write-all!"
C-q = ":write-quit-all!"

[editor]
true-color = true
default-yank-register = "+"
shell = ["bash", "-c"]
cursorline = true
continue-comments = false
bufferline = "always"
popup-border = "all"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.cursor-shape]
normal = "bar"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.auto-save]
focus-lost = true

[editor.soft-wrap]
enable = true
